name: deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Deploy
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USERNAME }}
        key: ${{ secrets.SCP_KEY }}
        passphrase: ${{ secrets.SCP_PASSPHRASE }}
        source: public/
        target: /var/www/public/
        rm: true
